wandb_version: 1

epochs:
  desc: null
  value: 30
lr:
  desc: null
  value: 0.001
Architecture:
  desc: null
  value: Fam
dataset:
  desc: null
  value: Pfam Seed
_wandb:
  desc: null
  value:
    python_version: 3.10.0
    cli_version: 0.16.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1719258660.968278
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 16
      - 23
      4: 3.10.0
      5: 0.16.3
      8:
      - 5
      13: linux-x86_64
