name: psalm
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - aws-c-auth=0.6.28
  - aws-c-cal=0.5.27
  - aws-c-common=0.8.20
  - aws-c-compression=0.2.17
  - aws-c-event-stream=0.3.0
  - aws-c-http=0.7.8
  - aws-c-io=0.13.26
  - aws-c-mqtt=0.8.13
  - aws-c-s3=0.3.4
  - aws-c-sdkutils=0.1.10
  - aws-checksums=0.1.16
  - aws-crt-cpp=0.20.2
  - aws-sdk-cpp=1.10.57
  - biopython=1.83
  - blas=1.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2024.2.2
  - certifi=2024.2.2
  - charset-normalizer=3.1.0
  - colorama=0.4.6
  - contourpy=1.2.1
  - cuda-cudart=11.7.99
  - cuda-cupti=11.7.101
  - cuda-libraries=11.7.1
  - cuda-nvrtc=11.7.99
  - cuda-nvtx=11.7.91
  - cuda-runtime=11.7.1
  - cycler=0.12.1
  - dbus=1.13.18
  - expat=2.5.0
  - ffmpeg=4.3
  - filelock=3.12.2
  - fontconfig=2.14.2
  - fonttools=4.51.0
  - freetype=2.12.1
  - glib=2.80.2
  - glib-tools=2.80.2
  - gmp=6.2.1
  - gmpy2=2.1.2
  - gnutls=3.6.13
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - icu=58.2
  - idna=3.4
  - intel-openmp=2023.1.0
  - jinja2=3.1.2
  - jpeg=9e
  - keyutils=1.6.1
  - kiwisolver=1.4.5
  - krb5=1.20.1
  - lame=3.100
  - lcms2=2.15
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang=10.0.1
  - libcublas=11.10.3.66
  - libcufft=10.7.2.124
  - libcufile=1.6.1.9
  - libcurand=10.3.2.106
  - libcurl=8.1.2
  - libcusolver=11.4.0.1
  - libcusparse=11.7.4.91
  - libdeflate=1.17
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.5.0
  - libffi=3.4.2
  - libgcc-ng=13.1.0
  - libglib=2.80.2
  - libgomp=13.1.0
  - libiconv=1.17
  - libllvm10=10.0.1
  - libllvm14=14.0.6
  - libnghttp2=1.52.0
  - libnpp=11.7.4.75
  - libnsl=2.0.0
  - libnvjpeg=11.8.0.2
  - libpng=1.6.39
  - libpq=12.17
  - libsqlite=3.42.0
  - libssh2=1.11.0
  - libstdcxx-ng=13.1.0
  - libtiff=4.5.0
  - libuuid=2.38.1
  - libwebp-base=1.4.0
  - libxcb=1.16
  - libxkbcommon=1.0.1
  - libxml2=2.9.14
  - libzlib=1.2.13
  - llvmlite=0.42.0
  - markupsafe=2.1.3
  - matplotlib=3.8.4
  - matplotlib-base=3.8.4
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.6
  - mkl_random=1.2.2
  - mpc=1.3.1
  - mpfr=4.2.0
  - mpmath=1.3.0
  - munkres=1.1.4
  - ncurses=6.4
  - nettle=3.6
  - networkx=3.1
  - nspr=4.35
  - nss=3.89.1
  - numba=0.59.1
  - numpy=1.24.3
  - numpy-base=1.24.3
  - openh264=2.1.1
  - openjpeg=2.5.0
  - openssl=3.3.0
  - packaging=24.0
  - pcre2=10.43
  - pillow=10.3.0
  - pip=23.1.2
  - ply=3.11
  - pthread-stubs=0.4
  - pyparsing=3.0.9
  - pyqt=5.15.10
  - pyqt5-sip=12.13.0
  - pysocks=1.7.1
  - python=3.11.4
  - python-dateutil=2.9.0
  - python_abi=3.11
  - pytorch=2.0.1
  - pytorch-cuda=11.7
  - pytorch-mutex=1.0
  - qt-main=5.15.2
  - readline=8.2
  - requests=2.31.0
  - s2n=1.3.45
  - setuptools=67.7.2
  - sip=6.7.12
  - six=1.16.0
  - sqlite=3.45.3
  - sympy=1.12
  - tbb=2021.8.0
  - tk=8.6.12
  - tomli=2.0.1
  - torchdata=0.6.1
  - torchtext=0.15.2
  - torchtriton=2.0.0
  - torchvision=0.15.2
  - tornado=6.4
  - tqdm=4.65.0
  - typing_extensions=4.6.3
  - tzdata=2023c
  - urllib3=2.0.3
  - wheel=0.40.0
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xz=5.2.6
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
      - fair-esm==2.0.0
